### ISSUE TITLE
尚未支持docker api v1.41 upwards

### ISSUE THREAD

**Issue by singlaive** [zeromake/docker-debug#18]
在Ubuntu环境下载运行，得到如下错误：
~$ ./docker-debug axon bash -l
ERRO[0000] Error: Error response from daemon: client version 1.41 is too new. Maximum supported API version is 1.40

作者百忙中可否抽出些时间添加支持？

**Comment by zeromake** [comment]
@singlaive 参考 #9 修改 version 为 1.40 即可
cat ~/.docker-debug/config.toml
``` toml
version = "0.7.7"
mount_dir = "/mnt/container"
image = "nicolaka/netshoot:latest"
timeout = 10000000000
config_default = "default"
read_timeout = -1

[config]
  [config.default]
    version = "1.41"
    host = "unix:///var/run/docker.sock"
    tls = false
    cert_dir = ""
    cert_password = ""
```
